import json
import hashlib
from datetime import datetime


def compile_ai_package(graph_state: dict, output_path: str, repo_path: str = None):
    from dm.cli.context import build, format_json

    findings_raw = graph_state.get("audit_findings", {})
    findings_list = []
    for detector_name, det_findings in findings_raw.items():
        for f in det_findings:
            findings_list.append({
                "detector": detector_name,
                "rule_id": f.rule_id,
                "severity": f.severity,
                "file": f.file,
                "line": f.line,
                "description": f.description,
                "confidence": f.confidence,
                "suggested_fix": f.suggested_fix,
            })

    project_context = {}
    if repo_path:
        project_context = build(repo_path)

    pkg = {
        "aether_version": "1.0.0",
        "generated_at": datetime.utcnow().isoformat(),
        "graph_version": graph_state.get("graph_version", "1.0.0"),
        "project_context": project_context,
        "agent_prompt": format_prompt_from(project_context) if project_context else "",
        "genome": {
            "nodes_count": len(graph_state.get("files", [])) + (1 if graph_state.get("repo_node") else 0),
            "edges_count": graph_state.get("edge_count", 0),
            "facts_count": len(graph_state.get("facts", [])),
            "verifications_count": len(graph_state.get("verifications", [])),
            "findings_count": len(findings_list),
            "languages": list(set(f.get("properties", {}).get("extension", "") for f in graph_state.get("files", []))),
        },
        "nodes": [],
        "edges": [],
        "facts": graph_state.get("facts", []),
        "verifications": graph_state.get("verifications", []),
        "findings": findings_list,
    }

    repo = graph_state.get("repo_node")
    if repo:
        pkg["nodes"].append({
            "id": repo["id"], "kind": repo["kind"],
            "name": repo["name"], "properties": repo["properties"],
        })

    for f in graph_state.get("files", []):
        pkg["nodes"].append({
            "id": f["id"], "kind": f["kind"], "name": f["name"],
            "properties": {k: v for k, v in f.get("properties", {}).items() if k != "content_preview"},
        })

    for e in graph_state.get("edges", []):
        pkg["edges"].append({
            "source_id": e["source_id"], "target_id": e["target_id"], "kind": e["kind"],
        })

    raw = json.dumps(pkg, indent=2, default=str)
    pkg["checksum"] = hashlib.sha256(raw.encode()).hexdigest()[:16]

    with open(output_path, "w", encoding="utf-8") as f:
        json.dump(pkg, f, indent=2, default=str)
    return output_path


def format_prompt_from(ctx: dict) -> str:
    if not ctx:
        return ""
    lines = [
        "# Project Context — autogenerated by Dark Matter",
        f"Project: {ctx.get('project', {}).get('name', 'unknown')}",
    ]
    if ctx.get("summary"):
        lines.append(f"Summary: {ctx['summary'][:200]}")
    if ctx.get("language"):
        lines.append(f"Languages: {', '.join(ctx['language'])}")
    if ctx.get("frameworks"):
        lines.append(f"Frameworks: {', '.join(ctx['frameworks'])}")
    if ctx.get("entry_points"):
        lines.append("Entry points:")
        for ep in ctx["entry_points"]:
            lines.append(f"  {ep}")
    run_cmd = ctx.get("project", {}).get("run_command")
    test_cmd = ctx.get("project", {}).get("test_command")
    if run_cmd:
        lines.append(f"Run: {run_cmd}")
    if test_cmd:
        lines.append(f"Test: {test_cmd}")
    if ctx.get("dependencies"):
        lines.append(f"Dependencies ({len(ctx['dependencies'])}):")
        for i, (n, v) in enumerate(sorted(ctx["dependencies"].items())):
            if i >= 10:
                break
            lines.append(f"  {n}: {v}")
    if ctx.get("env_vars"):
        lines.append(f"Env vars: {', '.join(sorted(ctx['env_vars'])[:8])}")
    if ctx.get("architecture"):
        lines.append(f"Architecture: {', '.join(ctx['architecture'])}")
    lines.append("---")
    lines.append("Read this before making changes. Follow existing patterns.")
    lines.append("Run `dm audit -p --severity high` before shipping.")
    return "\n".join(lines)
